#!/bin/bash

# 根据超算类型申请计算节点


#-------------------------------- 获取帮助 --------------------------------
get_help() {
  script_name=$(basename "${0}")

  echo -e "\nUsage: ${script_name} num_cpu"

  echo -e "Apply cal node in Pi / SiYuan HPC."

  echo -e "\nOptions:"
  echo "    -h, --help       show this help message and exit"
  echo "    num_cpu          number of CPU"

  echo -e "\nAuthor: YSL."
}


#-------------------------------- 主函数 --------------------------------
if [[ $# -gt 1 ]]; then
  $ECHO "Error: Too many arguments.\n"
  get_help

elif [[ $1 == "-h" || $1 == "--help" || $# -eq 0 ]]; then
  get_help

elif [[ $HOSTNAME =~ "sylogin" ]]; then
  srun -p 64c512g -n "$1" --pty /bin/bash

elif [[ $HOSTNAME =~ "pilogin" ]]; then
  srun -p cpu -n "$1" --pty /bin/bash

else
  echo -e "Error: Unsupported hostname: $HOSTNAME. Only pi / siyuan supported!\n"
  get_help
fi
