#!/bin/bash

# 检查 VASP 计算目录是否完成计算

script_name=$(basename "$0")
show_help() {
  echo "Check VASP calculation folder is completed or not."
  echo -e "\nUsage: ${script_name} [folders...]"
  echo -e "\nOptions:"
  echo "    -h, --help    show this help message and exit"
  echo "    folders       VASP calculation folders"
}

if [ $# -eq 0 ]; then
  show_help
  exit 1
fi

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  show_help
  exit 0
fi


check_done() {
  for dir in "$@"; do
    outcar_fn="$dir/OUTCAR"

    if [ ! -f "$outcar_fn" ]; then
      echo "Folder $dir OUTCAR doesn't exist!"
    else
      if grep -q "Total CPU time used" "$outcar_fn"; then
        echo "Folder $dir VASP Calculation is completed!"
      else
        echo "Folder $dir VASP Calculation isn't completed."
      fi
    fi
  done
}


if [[ "$1" == "." ]]; then
  for item in ./*; do
    if [[ -d ${item} ]]; then
      item=$(basename "${item}")
      check_done "${item}"
    fi
  done
else
  check_done "$@"
fi
