#!/bin/bash


#-------------------------------- 检查 VASP 计算目录是否完成计算 --------------------------------
check_completed() {
  completed_dirs=()
  uncompleted_dirs=()
  for dir in "$@"; do
    outcar_fn="$dir/OUTCAR"

    dir=$(basename "${dir}")

    if [ ! -f "$outcar_fn" ]; then
      echo "Folder $dir OUTCAR doesn't exist!"
    else
      if grep -q "Total CPU time used" "$outcar_fn"; then
        completed_dirs+=("$dir")
      else
        uncompleted_dirs+=("$dir")
      fi
    fi
  done

  echo "Completed dirs (${#completed_dirs[@]}):"
  for dir in "${completed_dirs[@]}"; do
    echo "  $dir"
  done

  if [[ ${#uncompleted_dirs[@]} -eq 0 ]]; then
    echo -e "\nAll VASP calculation dirs are completed!"
  else
    echo -e "\nUncompleted dirs (${#uncompleted_dirs[@]}):"
    for dir in "${uncompleted_dirs[@]}"; do
      echo "  $dir"
    done
  fi
}



#-------------------------------- 获取帮助 --------------------------------
get_help() {
  script_name=$(basename "$0")

  echo -e "\nUsage: ${script_name} [dirs...]"

  echo -e "\nCheck VASP calculation dirs whether completed."

  echo -e "\nOptions:"
  echo "    -h, --help    show this help message and exit"
  echo "    dirs          VASP calculation dirs"

  echo -e "\nExamples:"
  echo "    ${script_name} \${PWD}       # 当前目录"
  echo "    ${script_name} test1        # 单个目录"
  echo "    ${script_name} test1 test2  # 多个目录"
  echo "    ${script_name} .            # 当前目录下的所有子目录"

  exit 0
}


#-------------------------------- 主函数 --------------------------------
if [ $# -eq 0 ]; then
  get_help
  exit 0

elif [[ "$1" == "-h" || "$1" == "--help" ]]; then
  get_help

elif [[ "$1" == "." ]]; then
  for item in ./*; do
    if [[ -d ${item} ]]; then
      item=$(basename "${item}")
      check_completed "${item}"
    fi
  done

else
  check_completed "$@"
fi
