#!/bin/bash


#-------------------------------- 检查 VASP 弛豫计算目录是否达到收敛精度 --------------------------------
check_converged() {
  converged_dirs=()
  unconverged_dirs=()
  for dir in "$@"; do
    outcar_fn="$dir/OUTCAR"

    dir=$(basename "${dir}")

    if [ ! -f "$outcar_fn" ]; then
      echo "Folder $dir OUTCAR doesn't exsists!"
    else
      if grep -q "reached required accuracy" "$outcar_fn"; then
        converged_dirs+=("$dir")
      else
        unconverged_dirs+=("$dir")
      fi
    fi
  done

  echo "Converged dirs:"
  for dir in "${converged_dirs[@]}"; do
    echo "  $dir"
  done

  if [[ ${#unconverged_dirs[@]} -eq 0 ]]; then
    echo -e "\nAll VASP relaxation/optimization calulations dirs are converged!"
  else
    echo -e "\nUnconverged dirs:"
    for dir in "${unconverged_dirs[@]}"; do
      echo "  $dir"
    done
  fi

}


#-------------------------------- 获取帮助 --------------------------------
get_help() {
  script_name=$(basename "$0")

  echo -e "\nUsage: ${script_name} [dirs...]"

  echo -e "\nCheck VASP relaxation/optimization calculation dirs whether converged."

  echo -e "\nOptions:"
  echo "    -h, --help    show this help message and exit"
  echo "    dirs          VASP calculation dirs"

  echo -e "\nExamples:"
  echo "    ${script_name} \${PWD}       # 当前目录"
  echo "    ${script_name} test1        # 单个目录"
  echo "    ${script_name} test1 test2  # 多个目录"
  echo "    ${script_name} .            # 当前目录下的所有子目录"

  exit 0
}


#-------------------------------- 主函数 --------------------------------
if [ $# -eq 0 ]; then
  get_help
  exit 0

elif [[ "$1" == "-h" || "$1" == "--help" ]]; then
  get_help

elif [[ "$1" == "." ]]; then
  for item in ./*; do
    if [[ -d ${item} ]]; then
      item=$(basename "${item}")
      check_converged "${item}"
    fi
  done

else
  check_converged "$@"
fi
