#!/bin/bash

# 检查 VASP 弛豫计算目录是否达到收敛精度

script_name=$(basename "$0")
show_help() {
  echo "Check VASP structure optimization calculation folder is converged or not."
  echo -e "\nUsage: ${script_name} [folders...]"
  echo -e "\nOptions:"
  echo "    -h, --help    show this help message and exit"
  echo "    folders       VASP calculation folders"
}

if [ $# -eq 0 ]; then
  show_help
  exit 1
fi

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  show_help
  exit 0
fi


check_opt() {
  for dir in "$@"; do
    outcar_fn="$dir/OUTCAR"

    if [ ! -f "$outcar_fn" ]; then
      echo "Folder $dir OUTCAR doesn't exsists!"
    else
      if grep -q "reached required accuracy" "$outcar_fn"; then
        echo "Folder $dir VASP Structure Optimization Calulation is converged!"
      else
        echo "Folder $dir VASP Structure Optimization Calulation isn't converged."
      fi
    fi
  done
}


if [[ "$1" == "." ]]; then
  for item in ./*; do
    if [[ -d ${item} ]]; then
      item=$(basename "${item}")
      check_opt "${item}"
    fi
  done
else
  check_opt "$@"
fi