DIM = 4 4 4

BAND = 0. 0. 0.  0.5 -0.5 0.5  0.25 0.25 0.25  0. 0. 0.  0. 0. 0.5
# BAND = AUTO
BAND_LABELS = $\Gamma$ H P $\Gamma$ N
BAND_POINTS = 101

BAND_CONNECTION = .TRUE.
FORCE_SETS = READ
# FORCE_CONSTANTS = READ
