DIM = 4 4 4

BAND = 0. 0. 0.  0.333333 0.333333 0.  0.5 0. 0.  0. 0. 0.  0. 0. 0.5
# BAND = AUTO
BAND_LABELS = $\Gamma$ K M $\Gamma$ A
BAND_POINTS = 101

BAND_CONNECTION = .TRUE.
FORCE_SETS = READ
# FORCE_CONSTANTS = READ
